version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.4.1
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "xpack.security.transport.ssl.enabled=false"
      - "xpack.security.http.ssl.enabled=false"
    ports:
      - "19200:9200"
      - "9300:9300"
    deploy:
      resources:
        limits:
          memory: 2g