version: "3"
services:
  jeager:
    image: jaegertracing/all-in-one:1
    ports:
      - "16686:16686"
      - "14268:14268"

    networks:
      - "host_sendbox"
     

networks:
  host_sendbox:
    external: true
