version: "3.7"

services:

  postgres-serv:
    container_name: postgres
    hostname: postgres
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    networks:
      - postgres-network

  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "80:80"
    networks:
      - postgres-network
    depends_on:
      - postgres-serv
 
networks:
  postgres-network:
    driver: bridge
